language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_43030370c02a_key -iv $encrypted_43030370c02a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 118.24.152.130
script:
  - echo "hello world"
after_success:
  - ssh root@118.24.152.130
  - cd /home/www/blog # 打开git文件夹
  - git config user.name "antwork" # 修改name
  - git config user.email "antwork@126.com" # 修改email
  - git fetch --all  
  - git reset --hard origin/master 
  - git pull